const TAGLINES = [
  "Prank call like it's 1999 📞😈",
  "Don't forget to *67 first",
  "Serving no purpose for the better part of 3 decades",
  "Caller ID ruined everything",
  "Strike down upon scam callers with great vengeance",
  "Yes, a collect call for Mrs. Floyd from Mr. Floyd...",
  "CALLER IDENTITY BLOCKED",
  "Back in the days of landlines & answering machines",
  "You used to call me from a payphone",
  "No quarters or dimes required",
  "Haggling with pizza places over nickels"
];

const CHARACTERS = [
  {
    id: 'arnold',
    name: 'Arnold Soundboard',
    groups: [
      {
        label: 'Greetings',
        column: 'left',
        sounds: [
          { label: 'Good morning',       file: 'good-morning.mp3' },
          { label: 'Howdy, stranger',    file: 'howdy.mp3' },
          { label: 'Hi',                 file: 'hi.mp3' },
          { label: 'Hello',              file: 'hello-2.mp3' },
          { label: 'Helloooo?',          file: 'hello.mp3' },
          { label: "What's up?",         file: 'sup.mp3' },
          { label: 'How are you?',       file: 'how-are-you.mp3' },
          { label: 'Hasta la vista, baby',  file: 'hasta-la-vista.mp3' },
          { label: 'Goodbye',               file: 'bye.mp3' },
        ],
      },
      {
        label: 'Top Hits',
        column: 'left',
        sounds: [
          { label: 'Stop whining!',       file: 'stop-whining.mp3' },
          { label: 'You lack discipline', file: 'you-lack-discipline.mp3' },
          { label: 'Get to the choppa!',  file: 'choppa.mp3' },
          { label: "Bunch of questions",  file: 'questions-answer-me.mp3' },
          { label: 'Who is your daddy?',  file: 'who-is-your-daddy.mp3' },
          { label: 'Fist/Stomach',        file: 'stomach.mp3' },
        ],
      },
      {
        label: 'Cop Stuff',
        column: 'left',
        sounds: [
          { label: "I'm Det. John Kimble!",   file: 'det-kimble.mp3' },
          { label: "I'm a cop, you idiot!",   file: 'im-a-cop-you-idiot.mp3' },
          { label: "Hey, I'm a police officer", file: 'police-officer.mp3' },
          { label: 'Trust me',                file: 'trust-me.mp3' },
          { label: "You're under arrest",     file: 'arrest-2.mp3' },
          { label: "I'm pressing charges",    file: 'charges.mp3' },
          { label: 'Weekend in Jail',         file: 'jail.mp3' },
          { label: 'One of us is in trouble', file: 'one-of-us-is-in-deep-trouble.mp3' },
          { label: "Don't f***ing BS me",     file: 'dont-fing-bs-me.mp3' },
        ],
      },
      {
        label: 'Laughing',
        column: 'left',
        sounds: [
          { label: 'Chuckle',            file: 'chuckle.mp3' },
          { label: 'Haha',               file: 'haha.mp3' },
          { label: 'Crazy Laugh',        file: 'haha-crazy.mp3' },
        ],
      },

      {
        label: 'Responses',
        column: 'right',
        sounds: [
          { label: 'Yeah',               file: 'yeah.mp3' },
          { label: 'Sure',               file: 'sure.mp3' },
          { label: 'OK',                 file: 'ok.mp3' },
          { label: 'Yeeess',             file: 'yes.mp3' },
          { label: 'No deal',            file: 'no-deal.mp3' },
          { label: 'No!',                file: 'no.mp3' },
          { label: 'Negative',           file: 'negative.mp3' },
          { label: 'No no no no...',     file: 'no-no.mp3' },
          { label: 'No thank you',       file: 'no-thank-you.mp3' },
          { label: 'What?',              file: 'what.mp3' },
          { label: 'Huh?',               file: 'huh.mp3' },
          { label: 'Why?',               file: 'why.mp3' },
          { label: 'Why not?',           file: 'why-not.mp3' },
          { label: "I'm sorry",          file: 'sorry.mp3' },
          { label: 'I hear you',         file: 'hear.mp3' },
          { label: "Don't worry",        file: 'dont-worry.mp3' },
          { label: "It doesn't matter",  file: 'doesnt-matter.mp3' },
          { label: "I don't care",       file: 'idc.mp3' },
          { label: 'So?',                file: 'so.mp3' },
          { label: "What's your point?", file: 'whats-your-point.mp3' },
          { label: 'Proud of yourself?', file: 'proud-of-yourself.mp3' },
        ],
      },
      {
        label: 'Aggresive',
        column: 'right',
        sounds: [
          { label: 'Now!',                    file: 'now.mp3' },
          { label: 'Do it now!',              file: 'do-it-now.mp3' },
          { label: 'Stop it!',                file: 'stop-it.mp3' },
          { label: 'What the f***?!',         file: 'what-the-f.mp3' },
          { label: 'Shut up!',                file: 'shut-up.mp3' },
          { label: 'Shut the f*** up!',       file: 'shut-the-f-up.mp3' },
          { label: 'F*** you',                file: 'f-you.mp3' },
          { label: 'You idiot!',              file: 'idiot.mp3' },
          { label: 'You SoB!',                file: 'you-son-of-a-b.mp3' },
          { label: "I've got news...",        file: 'ive-got-news-for-you.mp3' },
          { label: 'Are you out of your mind?', file: 'are-you-out-of-your-mind.mp3' },
          { label: "Don't give me that crap!", file: 'dont-give-me-that-crap.mp3' },
          { label: 'BS',                       file: 'bs.mp3' },
          { label: 'Stop laughing!',           file: 'stop-laugh.mp3' },
          { label: "Look, I don't know you...", file: 'dky.mp3' },

        ],
      },
      {
        label: 'Random',
        column: 'full',
        sounds: [
          { label: "I'll be back",            file: 'ill-be-back.mp3' },
          { label: "I'll call you back",      file: 'call-you-back.mp3' },
          { label: "Don't call anybody",      file: 'dont-call-anybody.mp3' },
          { label: 'Who are you?',            file: 'who-are-you.mp3' },
          { label: 'Neural net processor',    file: 'neural-net-processor.mp3' },
          { label: 'California',              file: 'california.mp3' },
        ],
      },
    ],
  },
];
